const Permissions = Object.freeze({
  MANAGE_USERS: "MANAGE_USERS",
  ADD_USER: "ADD_USER",
  EDIT_USER: "EDIT_USER",
  DELETE_USER: "DELETE_USER",
  MANAGE_PRODUCTS: "MANAGE_PRODUCTS",
  ADD_PRODUCT: "ADD_PRODUCT",
  EDIT_PRODUCT: "EDIT_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  APPROVE_PRODUCT: "APPROVE_PRODUCT",
  MANAGE_PRODUCT_TYPES: "MANAGE_PRODUCT_TYPES",
  ADD_PRODUCT_TYPE: "ADD_PRODUCT_TYPE",
  EDIT_PRODUCT_TYPE: "EDIT_PRODUCT_TYPE",
  DELETE_PRODUCT_TYPE: "DELETE_PRODUCT_TYPE",
  APPROVE_PRODUCT_TYPE: "APPROVE_PRODUCT_TYPE",
  CART: "CART",
});
export default Permissions;
